web/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'autocomplete' => 'autocomplete#search'
  resources 'companies'

  root :to => 'companies#index'
end

web/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

web/app/models/company.rb
class Company < ApplicationRecord
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

web/app/controllers/autocomplete_controller.rb
class AutocompleteController < ApplicationController
  def search
    j = ActiveModel::SerializableResource.new(
      Company.where('company_name ILIKE ?', "%#{query}%").limit(10),
      each_serializer: CompaniesSuggestionsSerializer
    )
    render json: {status: 'ok', result: j}
  end

  def query
    permitted_params[:term]
  end

  def permitted_params
    params.permit(:term)
  end
end

web/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.order(:id).paginate(:page => params[:page], :per_page=>5)
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])

    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params
        .require(:company)
        .permit(
            Company.column_names.reject { |n| %i[id, created_at, updated_at].include?(n) }
        )
    end
end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/helpers/companies_helper.rb
module CompaniesHelper
end

web/app/views/companies/_form.html.erb
<%= form_with(model: @company, local: true) do |form| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <table>
      <tbody>
      <tr>
        <td>ID
          <%= @company.id %>
        </td>
      </tr><tr>
        <td>Created at
          <%= @company.created_at %>
        </td>
      </tr><tr>
        <td>Updated at
          <%= @company.updated_at %>
        </td>
      </tr>
        <% @company.attributes.reject { |a, _| %w[id created_at updated_at].include? a }.each do |key, val| %>
          <tr>
            <td>
            <%= form.label key.to_sym %>
            <%= form.text_field key.to_sym %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

web/app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= link_to 'Back', companies_path %>
<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

web/app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<%= will_paginate @companies%>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @companies.each do |company| %>
      <tr>
        <td><%= company.company_number %></td>
        <td><%= company.company_name %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @companies%>

<br>

<%= link_to 'New Company', new_company_path %>

web/app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

web/app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

<table>
  <tbody>
    <% @company.attributes.each do |key, val| %>
      <tr>
        <td><%= key %></td>
        <td><%= val %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CompaniesManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>